# -*- coding: utf-8 -*-
{
    'name': 'Mutuelle Santé',
    'version': '17.0.1.0.0',
    'summary': """ Mutuelle des douanes de Côte d'Ivoire """,
    'author': 'MUDCI',
    'website': 'https://www.douanes.ci/agent/mutuelles-des-agents',
    'category': 'Accounting/Accounting',
    'sequence': -1,
    'depends': ['base', 'web'],
    "data": [
        "security/group.xml",
        "security/ir.model.access.csv",
        "views/adh_localites_views.xml",
        "views/adh_beneficiaires_views.xml",
        "views/adh_polices_views.xml",
        "views/adh_contrats_views.xml",
        "views/adh_scolarises_views.xml",
        "views/adh_handicapes_views.xml",
        "views/adh_resiliations_views.xml",
        "views/adh_retraits_views.xml",
        "views/adh_suspensions_views.xml",
        "views/adh_leveesuspens_views.xml",
        "views/adherent_menu.xml",
        "data/mudci_demo.xml",
    ],
    # 'assets': {'web.assets_backend': ['mudci/static/src/**/*'],},
    # 'demo': ['demo/demo_mudci.xml'],
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
